site_name: AR-Biosphere ğŸ¦†ï¸ğŸŒ
theme:
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
    features::
      - search.suggest
      - search.highlight
      - content.tabs.link
plugins:
  - search
nav: 
    - Project Requirements: "index.md"
    - Software Design: "pages/software.md"
    - Project Management: "pages/management.md"
    - Teamwork: "pages/teamwork.mc"
docs_dir: ./docblueprint
site_dir: ./docs
